site_name: Guía de Arquitectura de Software
site_description: Guía completa de principios y patrones de arquitectura de software moderna
site_author: David R.

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - mermaid2

nav:
  - Inicio: index.md
  - Principios SOLID:
      - Visión general: solid/index.md
      - Responsabilidad Única: solid/single-responsibility.md
      - Abierto-Cerrado: solid/open-closed.md
      - Sustitución de Liskov: solid/liskov-substitution.md
      - Segregación de Interfaces: solid/interface-segregation.md
      - Inversión de Dependencias: solid/dependency-inversion.md
  - Patrones de Diseño:
      - Visión general: design-patterns/index.md
      - Patrones Creacionales: design-patterns/creational.md
      - Patrones Estructurales: design-patterns/structural.md
      - Patrones de Comportamiento: design-patterns/behavioral.md
  - Estilos Arquitectónicos:
      - Visión general: architecture/index.md
      - Arquitectura en Capas: architecture/layered/layered.md
      - Microservicios: 
          - Visión general: architecture/microservices/index.md
          - Principios de Diseño: architecture/microservices/principles.md
          - Patrones de Comunicación: architecture/microservices/communication.md
          - Estrategias de Despliegue: architecture/microservices/deployment.md
          - Estructura de Código: architecture/microservices/code-structure.md
  - Diseño Dirigido por el Dominio:
      - Visión general: ddd/index.md
      - Lenguaje Ubícuo: ddd/ubiquitous-language.md
      - Contextos Delimitados: ddd/bounded-contexts.md
      - Entidades y Objetos de Valor: ddd/entities-value-objects.md
      - Agregados: ddd/aggregates.md
      - Repositorios: ddd/repositories.md
      - Servicios de Dominio: ddd/domain-services.md
      - Servicios de Aplicación: ddd/application-services.md
      - Estructura de Código: ddd/code-structure.md
  - Mejores Prácticas:
      - Organización del Código: best-practices/code-organization.md
      - Gestión de Configuración: best-practices/configuration-management.md
      - Estrategias de Pruebas: best-practices/testing.md
      - Documentación: best-practices/documentation.md
  - Adopción en Equipo:
      - Registros de Decisiones de Arquitectura: team-adoption/adrs.md
      - Revisiones de Código: team-adoption/code-reviews.md
      - Compartición de Conocimiento: team-adoption/knowledge-sharing.md
      - Transición a Microservicios: team-adoption/microservices-transition.md
      - Implementación de DDD: team-adoption/ddd-implementation.md 