site_name: Guía de Arquitectura de Software
site_description: Guía completa de principios y patrones de arquitectura de software moderna
site_author: David R.

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.collapse
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.tooltips
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes
  - toc:
      permalink: true
      title: En esta página

plugins:
  - search
  - mermaid2
  - tags

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-github-handle
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/your-linkedin-handle
  consent:
    title: Uso de cookies
    description: >- 
      Utilizamos cookies para reconocer sus visitas y preferencias, así
      como para medir la efectividad de la documentación y si los usuarios
      encuentran lo que buscan. Con su consentimiento, nos está ayudando
      a mejorar nuestra documentación.

# URL para el repositorio de código
repo_url: https://github.com/yourusername/software-architecture-guide
repo_name: Software Architecture Guide
edit_uri: edit/main/docs/

nav:
  - Inicio: index.md
  - Glosario: glossary.md
  - Módulo 1 - Fundamentos:
      - Principios SOLID:
          - Visión general: solid/index.md
          - Responsabilidad Única: solid/single-responsibility.md
          - Abierto-Cerrado: solid/open-closed.md
          - Sustitución de Liskov: solid/liskov-substitution.md
          - Segregación de Interfaces: solid/interface-segregation.md
          - Inversión de Dependencias: solid/dependency-inversion.md
      - Patrones de Diseño:
          - Visión general: design-patterns/index.md
          - Patrones Creacionales: design-patterns/creational.md
          - Patrones Estructurales: design-patterns/structural.md
          - Patrones de Comportamiento: design-patterns/behavioral.md
  - Módulo 2 - Arquitecturas:
      - Visión general: architecture/index.md
      - Arquitectura en Capas: architecture/layered/layered.md
      - Microservicios: 
          - Visión general: architecture/microservices/index.md
          - Principios de Diseño: architecture/microservices/principles.md
          - Patrones de Comunicación: architecture/microservices/communication.md
          - Estrategias de Despliegue: architecture/microservices/deployment.md
          - Estructura de Código: architecture/microservices/code-structure.md
  - Módulo 3 - DDD:
      - Diseño Dirigido por el Dominio:
          - Introducción a DDD: ddd/index.md
          - Fundamentos para Principiantes:
              - Lenguaje Ubícuo: ddd/ubiquitous-language.md
              - Entidades y Objetos de Valor: ddd/entities-value-objects.md
              - Agregados: ddd/aggregates.md
              - Repositorios: ddd/repositories.md
          - Conceptos Intermedios:
              - Servicios de Dominio: ddd/domain-services.md
              - Servicios de Aplicación: ddd/application-services.md
          - Conceptos Avanzados:
              - Contextos Delimitados: ddd/bounded-contexts.md
              - Estructura de Código: ddd/code-structure.md
          - Aplicación Práctica:
              - Ejemplos Paso a Paso: ddd/examples.md
              - Guía de Implementación: team-adoption/ddd-implementation.md
  - Módulo 4 - Prácticas y Adopción:
      - Mejores Prácticas:
          - Organización del Código: best-practices/code-organization.md
          - Gestión de Configuración: best-practices/configuration-management.md
          - Estrategias de Pruebas: best-practices/testing.md
          - Documentación: best-practices/documentation.md
      - Adopción en Equipo:
          - Registros de Decisiones de Arquitectura: team-adoption/adrs.md
          - Revisiones de Código: team-adoption/code-reviews.md
          - Compartición de Conocimiento: team-adoption/knowledge-sharing.md
          - Transición a Microservicios: team-adoption/microservices-transition.md 